export type MarketplaceSeedItem = {
  id: string
  name: string
  description: string
  fullDescription: string
  type: "tool" | "integration" | "template" | "service" | "plan" | "capacity"
  category: "integration" | "template" | "service" | "plan" | "capacity"
  categories: string[]
  relatedArea: string
  minPlan: string
  status: "active" | "coming-soon" | "hidden"
  displayStatus: "included" | "premium" | "external" | "coming-soon" | "available"
  clientAction: string
  requiresLogin: boolean
  showInstitutional: boolean
  showDashboard: boolean
  views: number
  clicks: number
  activations: number
  lastAccess: string | null
}

const now = new Date().toISOString()

export const marketplaceSeedItems: MarketplaceSeedItem[] = [
  {
    id: "1",
    name: "Instancia Evolution API",
    description: "Conecte seu numero de WhatsApp via API profissional.",
    fullDescription:
      "A Evolution API permite que voce conecte seu numero de WhatsApp a sistemas externos de forma profissional e escalavel. Ideal para empresas que precisam de uma solucao robusta de comunicacao.",
    type: "tool",
    category: "integration",
    categories: ["integration", "external"],
    relatedArea: "atendimento",
    minPlan: "pro",
    status: "active",
    displayStatus: "external",
    clientAction: "Solicitar",
    requiresLogin: false,
    showInstitutional: true,
    showDashboard: true,
    views: 245,
    clicks: 87,
    activations: 32,
    lastAccess: now,
  },
  {
    id: "2",
    name: "Whaticket (Sistema de Suporte Multiatendimento)",
    description: "Atenda WhatsApp, Instagram e Facebook em um so lugar.",
    fullDescription:
      "O Whaticket e uma plataforma completa para atendimento multicanal, permitindo que sua equipe gerencie conversas de WhatsApp, Instagram e Facebook em uma unica interface.",
    type: "tool",
    category: "integration",
    categories: ["integration", "external"],
    relatedArea: "atendimento",
    minPlan: "pro",
    status: "active",
    displayStatus: "external",
    clientAction: "Contratar",
    requiresLogin: false,
    showInstitutional: true,
    showDashboard: true,
    views: 312,
    clicks: 145,
    activations: 56,
    lastAccess: now,
  },
  {
    id: "3",
    name: "Agenda Pro (Sistema de Agendamento)",
    description: "Plataforma completa para gerenciamento de horarios.",
    fullDescription:
      "O Agenda Pro e uma solucao completa para gerenciamento de agendamentos, ideal para clinicas, saloes e profissionais que trabalham com horarios marcados.",
    type: "tool",
    category: "integration",
    categories: ["integration", "external"],
    relatedArea: "agendamento",
    minPlan: "pro",
    status: "active",
    displayStatus: "external",
    clientAction: "Solicitar acesso",
    requiresLogin: false,
    showInstitutional: true,
    showDashboard: true,
    views: 198,
    clicks: 76,
    activations: 28,
    lastAccess: now,
  },
  {
    id: "4",
    name: "Template Premium - Fluxo de Pascoa com IA",
    description: "Campanha de Pascoa automatizada com IA para fidelizar clientes.",
    fullDescription:
      "Template pronto para campanhas de Pascoa, com mensagens personalizadas por IA e fluxos de interacao para aumentar o engajamento dos clientes durante o periodo festivo.",
    type: "template",
    category: "template",
    categories: ["template", "premium"],
    relatedArea: "marketing",
    minPlan: "pro",
    status: "active",
    displayStatus: "premium",
    clientAction: "Acesse a plataforma",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 156,
    clicks: 67,
    activations: 23,
    lastAccess: now,
  },
  {
    id: "5",
    name: "Servico: Criamos o fluxo ideal pra voce",
    description: "Nos diga sua necessidade e entregamos sua automacao pronta.",
    fullDescription:
      "Nossa equipe de especialistas analisa sua necessidade e desenvolve um fluxo de automacao personalizado para seu negocio, garantindo eficiencia e resultados.",
    type: "service",
    category: "service",
    categories: ["service", "external"],
    relatedArea: "all-areas",
    minPlan: "free",
    status: "active",
    displayStatus: "external",
    clientAction: "Solicitar proposta",
    requiresLogin: false,
    showInstitutional: true,
    showDashboard: true,
    views: 178,
    clicks: 89,
    activations: 12,
    lastAccess: now,
  },
  {
    id: "6",
    name: "Upgrade para Plano Avancado",
    description: "Desbloqueie solucoes exclusivas, mais execucoes e IA avancada.",
    fullDescription:
      "Aumente o potencial da sua conta com recursos avancados, maior capacidade de processamento e acesso a funcionalidades exclusivas de inteligencia artificial.",
    type: "plan",
    category: "plan",
    categories: ["plan", "premium"],
    relatedArea: "all-areas",
    minPlan: "free",
    status: "active",
    displayStatus: "premium",
    clientAction: "Ver planos",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 267,
    clicks: 134,
    activations: 45,
    lastAccess: now,
  },
  {
    id: "7",
    name: "Capacidade Extra - Execucoes Ilimitadas por 30 dias",
    description: "Ideal para periodos de pico ou campanhas intensas.",
    fullDescription:
      "Adicione capacidade ilimitada de execucoes por 30 dias, perfeito para periodos de alta demanda, campanhas sazonais ou lancamentos que exigem maior volume de interacoes.",
    type: "capacity",
    category: "capacity",
    categories: ["capacity", "premium"],
    relatedArea: "all-areas",
    minPlan: "free",
    status: "coming-soon",
    displayStatus: "coming-soon",
    clientAction: "Ativar",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 143,
    clicks: 56,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "8",
    name: "Integracao com Typebot Pro",
    description: "Use seus bots do Typebot direto na nossa plataforma.",
    fullDescription:
      "Conecte seus fluxos criados no Typebot diretamente a nossa plataforma, aproveitando o melhor dos dois mundos para criar experiencias interativas poderosas.",
    type: "integration",
    category: "integration",
    categories: ["integration", "coming-soon"],
    relatedArea: "atendimento",
    minPlan: "pro",
    status: "coming-soon",
    displayStatus: "coming-soon",
    clientAction: "Conectar",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 112,
    clicks: 34,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "9",
    name: "Modelo de Funil de Vendas com IA",
    description: "Geracao de leads com conteudo automatizado.",
    fullDescription:
      "Template completo de funil de vendas com geracao de conteudo por IA, segmentacao automatica de leads e sequencias de follow-up personalizadas.",
    type: "template",
    category: "template",
    categories: ["template", "recommended"],
    relatedArea: "vendas",
    minPlan: "pro",
    status: "active",
    displayStatus: "included",
    clientAction: "Acesse a plataforma",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 187,
    clicks: 78,
    activations: 31,
    lastAccess: now,
  },
  {
    id: "10",
    name: "Servico: Consultoria Express para montar seu fluxo ideal",
    description: "Agende uma reuniao e saia com seu sistema funcionando.",
    fullDescription:
      "Consultoria rapida e pratica onde nossos especialistas ajudam a configurar seu fluxo de automacao em tempo real, garantindo que voce saia da reuniao com seu sistema funcionando.",
    type: "service",
    category: "service",
    categories: ["service", "external"],
    relatedArea: "all-areas",
    minPlan: "free",
    status: "active",
    displayStatus: "external",
    clientAction: "Agendar consultoria",
    requiresLogin: false,
    showInstitutional: true,
    showDashboard: true,
    views: 132,
    clicks: 67,
    activations: 18,
    lastAccess: now,
  },
  {
    id: "11",
    name: "Template Premium - Campanha Black Friday",
    description: "Automacao completa para Black Friday com gatilhos de urgencia.",
    fullDescription:
      "Automacao completa para Black Friday com gatilhos de urgencia, mensagens inteligentes e foco em conversao durante campanhas sazonais.",
    type: "template",
    category: "template",
    categories: ["template", "premium", "recommended"],
    relatedArea: "marketing",
    minPlan: "pro",
    status: "active",
    displayStatus: "premium",
    clientAction: "Acesse a plataforma",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 0,
    clicks: 0,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "12",
    name: "Integracao com Zapier",
    description: "Conecte a plataforma com mais de 3000 aplicativos.",
    fullDescription:
      "Conecte a plataforma com mais de 3000 aplicativos por meio do Zapier, expandindo os fluxos operacionais com automacoes adicionais.",
    type: "integration",
    category: "integration",
    categories: ["integration", "recommended"],
    relatedArea: "all-areas",
    minPlan: "pro",
    status: "active",
    displayStatus: "included",
    clientAction: "Ativar",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 0,
    clicks: 0,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "13",
    name: "Template Premium - Campanha de Natal",
    description: "Automacao para vendas de fim de ano com IA.",
    fullDescription:
      "Automacao voltada para campanhas de fim de ano, com mensagens inteligentes e gatilhos para conversao em periodos festivos.",
    type: "template",
    category: "template",
    categories: ["template", "premium"],
    relatedArea: "marketing",
    minPlan: "pro",
    status: "active",
    displayStatus: "premium",
    clientAction: "Acesse a plataforma",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 0,
    clicks: 0,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "14",
    name: "Integracao com Hotmart",
    description: "Conecte sua conta Hotmart para automacao de infoprodutos.",
    fullDescription:
      "Conecte sua conta Hotmart para automatizar jornadas ligadas a infoprodutos, acesso e relacionamento com compradores.",
    type: "integration",
    category: "integration",
    categories: ["integration", "external"],
    relatedArea: "vendas",
    minPlan: "free",
    status: "active",
    displayStatus: "external",
    clientAction: "Solicitar proposta",
    requiresLogin: false,
    showInstitutional: true,
    showDashboard: true,
    views: 0,
    clicks: 0,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "15",
    name: "Template - Reengajamento de Clientes Inativos",
    description: "Recupere clientes que nao compram ha mais de 60 dias.",
    fullDescription:
      "Template voltado para reengajamento de clientes inativos com mensagens, triggers e conteudos inteligentes para recuperar oportunidades.",
    type: "template",
    category: "template",
    categories: ["template", "recommended"],
    relatedArea: "marketing",
    minPlan: "pro",
    status: "active",
    displayStatus: "included",
    clientAction: "Ativar",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 0,
    clicks: 0,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "16",
    name: "Integracao com RD Station",
    description: "Sincronize leads e automacoes com o RD Station.",
    fullDescription:
      "Sincronize leads e automacoes com o RD Station para alinhar operacao comercial, marketing e relacionamento na plataforma.",
    type: "integration",
    category: "integration",
    categories: ["integration", "coming-soon"],
    relatedArea: "marketing",
    minPlan: "pro",
    status: "coming-soon",
    displayStatus: "coming-soon",
    clientAction: "Conectar",
    requiresLogin: true,
    showInstitutional: true,
    showDashboard: true,
    views: 0,
    clicks: 0,
    activations: 0,
    lastAccess: null,
  },
]
