-- Consolidated schema for restoring the 2026-04-28 SaaS Solucoes backup.
-- Run this once on a fresh Supabase project before running scripts/supabase-restore-backup.mjs.

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

create table if not exists public.users (
  id uuid primary key,
  created_at timestamptz default now(),
  email text not null,
  status text default 'active',
  plan text default 'gratuito',
  plan_id integer,
  onboarding_completed boolean not null default false,
  user_type text default 'client',
  last_sign_in_at timestamptz,
  name text,
  updated_at timestamptz default now()
);

create table if not exists public.profiles (
  id uuid primary key,
  name text,
  bio text,
  phone text,
  job_title text,
  company text,
  website text,
  location text,
  avatar_url text,
  preferences jsonb,
  profile_complete boolean default false,
  company_name text,
  company_size text,
  industry text,
  address text,
  city text,
  state text,
  country text,
  postal_code text,
  social_links jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  email text,
  username text,
  full_name text
);

create table if not exists public.solutions (
  id integer generated by default as identity primary key,
  slug text unique,
  name text not null,
  description text,
  category text,
  icon text,
  color text,
  is_active boolean default false,
  is_recommended boolean default false,
  is_premium boolean default false,
  premium_plan text,
  activations integer default 0,
  is_available boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.plans (
  id integer generated by default as identity primary key,
  name text not null,
  price numeric,
  description text,
  created_at timestamptz default now(),
  code text unique,
  features text,
  interval text,
  billing_cycle text,
  is_active boolean default true,
  is_featured boolean default false,
  max_solutions integer default 5,
  sort_order integer default 0,
  updated_at timestamptz default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_plan_id_fkey'
  ) then
    alter table public.users
      add constraint users_plan_id_fkey
      foreign key (plan_id) references public.plans(id);
  end if;
end $$;

create table if not exists public.plan_solutions (
  id integer generated by default as identity primary key,
  plan_id integer references public.plans(id) on delete cascade,
  solution_id integer references public.solutions(id) on delete cascade,
  created_at timestamptz default now(),
  unique (plan_id, solution_id)
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  plan_id integer references public.plans(id),
  status text default 'active',
  current_period_start timestamptz default now(),
  current_period_end timestamptz,
  cancel_at_period_end boolean default false,
  canceled_at timestamptz,
  payment_method text,
  payment_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  titulo text,
  slug text unique,
  conteudo text,
  data_publicacao timestamptz,
  imagem_capa text,
  publicado boolean default false,
  description text
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text not null,
  type text default 'notification',
  category text,
  user_target uuid,
  plan_target text,
  role_target text default 'all',
  expires_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  notification_id uuid references public.notifications(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz default now(),
  unique (user_id, notification_id)
);

create table if not exists public.email_verification (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  email text not null,
  token text,
  verified boolean default false,
  expires_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.marketplace_items (
  id text primary key,
  name text not null,
  description text not null,
  type text not null default 'service',
  categories text[] not null default '{}',
  status text not null default 'active',
  requires_login boolean not null default false,
  created_at timestamptz default now(),
  views integer not null default 0,
  clicks integer not null default 0,
  activations integer not null default 0,
  last_access timestamptz,
  full_description text,
  category text,
  related_area text,
  min_plan text default 'free',
  client_action text default 'Ver mais',
  show_institutional boolean not null default true,
  show_dashboard boolean not null default true,
  display_status text not null default 'available',
  updated_at timestamptz default now()
);

create table if not exists public.migrations (
  id uuid primary key default gen_random_uuid(),
  filename text not null,
  executed_at timestamptz default now(),
  executed_by uuid,
  status text not null,
  execution_time integer,
  error_message text
);

create or replace view public.user_profiles_view as
select
  u.id,
  u.email,
  u.name,
  u.status,
  u.plan,
  u.user_type,
  u.last_sign_in_at,
  u.created_at,
  u.updated_at,
  p.bio,
  p.phone,
  p.job_title,
  p.company,
  p.website,
  p.location,
  p.avatar_url,
  p.preferences,
  p.profile_complete,
  p.company_name,
  p.company_size,
  p.industry,
  p.address,
  p.city,
  p.state,
  p.country,
  p.postal_code,
  p.social_links,
  p.username
from public.users u
left join public.profiles p on p.id = u.id;

create or replace function public.touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at before update on public.users
for each row execute function public.touch_updated_at();

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists plans_touch_updated_at on public.plans;
create trigger plans_touch_updated_at before update on public.plans
for each row execute function public.touch_updated_at();

drop trigger if exists subscriptions_touch_updated_at on public.subscriptions;
create trigger subscriptions_touch_updated_at before update on public.subscriptions
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger as $$
declare
  resolved_plan_id integer;
  resolved_plan_code text;
begin
  select id, coalesce(code, 'gratuito')
    into resolved_plan_id, resolved_plan_code
  from public.plans
  where lower(coalesce(code, name)) = lower(coalesce(new.raw_user_meta_data->>'plan', 'gratuito'))
  order by id
  limit 1;

  if resolved_plan_code is null then
    resolved_plan_code := 'gratuito';
  end if;

  insert into public.users (id, email, name, user_type, status, plan, plan_id, onboarding_completed, last_sign_in_at)
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data->>'name', new.email),
    coalesce(new.raw_user_meta_data->>'user_type', 'client'),
    'active',
    resolved_plan_code,
    resolved_plan_id,
    false,
    new.last_sign_in_at
  )
  on conflict (id) do nothing;

  insert into public.profiles (id, email, name)
  values (new.id, lower(new.email), coalesce(new.raw_user_meta_data->>'name', new.email))
  on conflict (id) do nothing;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.solutions enable row level security;
alter table public.plans enable row level security;
alter table public.plan_solutions enable row level security;
alter table public.subscriptions enable row level security;
alter table public.posts enable row level security;
alter table public.notifications enable row level security;
alter table public.user_notifications enable row level security;
alter table public.email_verification enable row level security;
alter table public.marketplace_items enable row level security;
alter table public.migrations enable row level security;

create policy "Public can read active solutions" on public.solutions
  for select using (true);
create policy "Public can read active plans" on public.plans
  for select using (true);
create policy "Public can read plan solutions" on public.plan_solutions
  for select using (true);
create policy "Public can read published posts" on public.posts
  for select using (publicado = true);
create policy "Public can read visible marketplace items" on public.marketplace_items
  for select using (status <> 'hidden' and (show_institutional = true or show_dashboard = true));

create policy "Users can read own user" on public.users
  for select using (auth.uid() = id);
create policy "Users can update own user" on public.users
  for update using (auth.uid() = id);
create policy "Users can read own profile" on public.profiles
  for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.solutions, public.plans, public.plan_solutions, public.posts, public.marketplace_items to anon, authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
