// Dados iniciais para o Marketplace
export const marketplaceProducts = [
  {
    id: "1",
    name: "Instância Evolution API",
    description: "Conecte seu número de WhatsApp via API profissional.",
    fullDescription:
      "A Evolution API permite que você conecte seu número de WhatsApp a sistemas externos de forma profissional e escalável. Ideal para empresas que precisam de uma solução robusta de comunicação.",
    category: "integration",
    relatedArea: "atendimento",
    minPlan: "pro",
    status: "active",
    clientAction: "Solicitar",
    showInstitutional: true,
    showDashboard: true,
    views: 245,
    clicks: 87,
    activations: 32,
    lastAccess: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Whaticket (Sistema de Suporte Multiatendimento)",
    description: "Atenda WhatsApp, Instagram e Facebook em um só lugar.",
    fullDescription:
      "O Whaticket é uma plataforma completa para atendimento multicanal, permitindo que sua equipe gerencie conversas de WhatsApp, Instagram e Facebook em uma única interface.",
    category: "integration",
    relatedArea: "atendimento",
    minPlan: "pro",
    status: "active",
    clientAction: "Contratar",
    showInstitutional: true,
    showDashboard: true,
    views: 312,
    clicks: 145,
    activations: 56,
    lastAccess: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Agenda Pro (Sistema de Agendamento)",
    description: "Plataforma completa para gerenciamento de horários.",
    fullDescription:
      "O Agenda Pro é uma solução completa para gerenciamento de agendamentos, ideal para clínicas, salões e profissionais que trabalham com horários marcados.",
    category: "integration",
    relatedArea: "agendamento",
    minPlan: "pro",
    status: "active",
    clientAction: "Solicitar acesso",
    showInstitutional: true,
    showDashboard: true,
    views: 198,
    clicks: 76,
    activations: 28,
    lastAccess: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Template Premium - Fluxo de Páscoa com IA",
    description: "Campanha de Páscoa automatizada com IA para fidelizar clientes.",
    fullDescription:
      "Template pronto para campanhas de Páscoa, com mensagens personalizadas por IA e fluxos de interação para aumentar o engajamento dos clientes durante o período festivo.",
    category: "template",
    relatedArea: "marketing",
    minPlan: "pro",
    status: "active",
    clientAction: "Acesse a plataforma",
    showInstitutional: true,
    showDashboard: true,
    views: 156,
    clicks: 67,
    activations: 23,
    lastAccess: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Serviço: Criamos o fluxo ideal pra você",
    description: "Nos diga sua necessidade e entregamos sua automação pronta.",
    fullDescription:
      "Nossa equipe de especialistas analisa sua necessidade e desenvolve um fluxo de automação personalizado para seu negócio, garantindo eficiência e resultados.",
    category: "service",
    relatedArea: "all-areas",
    minPlan: "free",
    status: "active",
    clientAction: "Solicitar proposta",
    showInstitutional: true,
    showDashboard: true,
    views: 178,
    clicks: 89,
    activations: 12,
    lastAccess: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Upgrade para Plano Avançado",
    description: "Desbloqueie soluções exclusivas, mais execuções e IA avançada.",
    fullDescription:
      "Aumente o potencial da sua conta com recursos avançados, maior capacidade de processamento e acesso a funcionalidades exclusivas de inteligência artificial.",
    category: "plan",
    relatedArea: "all-areas",
    minPlan: "free",
    status: "active",
    clientAction: "Ver planos",
    showInstitutional: true,
    showDashboard: true,
    views: 267,
    clicks: 134,
    activations: 45,
    lastAccess: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Capacidade Extra – Execuções Ilimitadas por 30 dias",
    description: "Ideal para períodos de pico ou campanhas intensas.",
    fullDescription:
      "Adicione capacidade ilimitada de execuções por 30 dias, perfeito para períodos de alta demanda, campanhas sazonais ou lançamentos que exigem maior volume de interações.",
    category: "capacity",
    relatedArea: "all-areas",
    minPlan: "free",
    status: "coming-soon",
    clientAction: "Ativar",
    showInstitutional: true,
    showDashboard: true,
    views: 143,
    clicks: 56,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "8",
    name: "Integração com Typebot Pro",
    description: "Use seus bots do Typebot direto na nossa plataforma.",
    fullDescription:
      "Conecte seus fluxos criados no Typebot diretamente à nossa plataforma, aproveitando o melhor dos dois mundos para criar experiências interativas poderosas.",
    category: "integration",
    relatedArea: "atendimento",
    minPlan: "pro",
    status: "coming-soon",
    clientAction: "Conectar",
    showInstitutional: true,
    showDashboard: true,
    views: 112,
    clicks: 34,
    activations: 0,
    lastAccess: null,
  },
  {
    id: "9",
    name: "Modelo de Funil de Vendas com IA",
    description: "Geração de leads com conteúdo automatizado.",
    fullDescription:
      "Template completo de funil de vendas com geração de conteúdo por IA, segmentação automática de leads e sequências de follow-up personalizadas.",
    category: "template",
    relatedArea: "vendas",
    minPlan: "pro",
    status: "active",
    clientAction: "Acesse a plataforma",
    showInstitutional: true,
    showDashboard: true,
    views: 187,
    clicks: 78,
    activations: 31,
    lastAccess: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Serviço: Consultoria Express para montar seu fluxo ideal",
    description: "Agende uma reunião e saia com seu sistema funcionando.",
    fullDescription:
      "Consultoria rápida e prática onde nossos especialistas ajudam a configurar seu fluxo de automação em tempo real, garantindo que você saia da reunião com seu sistema funcionando.",
    category: "service",
    relatedArea: "all-areas",
    minPlan: "free",
    status: "active",
    clientAction: "Agendar consultoria",
    showInstitutional: true,
    showDashboard: true,
    views: 132,
    clicks: 67,
    activations: 18,
    lastAccess: new Date().toISOString(),
  },
]
