import { createClient } from "@supabase/supabase-js"

// Configuração do cliente Supabase
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || ""
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || ""

const supabase = createClient(supabaseUrl, supabaseServiceKey)

// Lista de soluções do catálogo antigo
const solucoes = [
  {
    id: "autoatendimento-ia",
    nome: "Autoatendimento com IA",
    descricao: "Cliente interage com um fluxo que entende a intenção e responde sozinho.",
    categoria: "atendimento",
    icone: "Bot",
    cor: "bg-blue-500/10 text-blue-500",
    status: "ativo",
    bloqueado: false,
  },
  {
    id: "recuperar-cliente",
    nome: "Recuperar Cliente Inativo",
    descricao: "Reativa contatos que pararam de responder com mensagem personalizada.",
    categoria: "vendas",
    icone: "Users",
    cor: "bg-green-500/10 text-green-500",
    status: "ativo",
    bloqueado: false,
  },
  {
    id: "agendamento-rapido",
    nome: "Agendamento Rápido",
    descricao: "Permite que o cliente marque um horário via mensagem automática.",
    categoria: "agendamento",
    icone: "Calendar",
    cor: "bg-purple-500/10 text-purple-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "pesquisa-satisfacao",
    nome: "Pesquisa de Satisfação",
    descricao: "Coleta avaliação de atendimento ou serviço com emojis ou notas.",
    categoria: "feedback",
    icone: "ThumbsUp",
    cor: "bg-orange-500/10 text-orange-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "email-marketing",
    nome: "E-mail Marketing Automatizado",
    descricao: "Envia campanhas automáticas como boas-vindas e promoções em datas especiais.",
    categoria: "vendas",
    icone: "Mail",
    cor: "bg-red-500/10 text-red-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "funil-vendas",
    nome: "Funil de Vendas Automatizado",
    descricao: "Alimenta o cliente com conteúdo até a compra com mensagens automáticas.",
    categoria: "vendas",
    icone: "PieChart",
    cor: "bg-cyan-500/10 text-cyan-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "bot-comentarios",
    nome: "Bot para Interações em Comentários",
    descricao: "Responde automaticamente comentários no Instagram/Facebook com base em palavras-chave.",
    categoria: "atendimento",
    icone: "Zap",
    cor: "bg-yellow-500/10 text-yellow-500",
    status: "recomendado",
    bloqueado: false,
  },
  {
    id: "confirmacao-consulta",
    nome: "Confirmação de Consulta",
    descricao: "Lembra o cliente da consulta com botão para confirmar ou reagendar.",
    categoria: "agendamento",
    icone: "Clock",
    cor: "bg-indigo-500/10 text-indigo-500",
    status: "recomendado",
    bloqueado: false,
  },
  {
    id: "resposta-automatica",
    nome: "Resposta Automática Inteligente",
    descricao: "Responde perguntas frequentes com base em um banco de conhecimento personalizado.",
    categoria: "atendimento",
    icone: "MessageSquare",
    cor: "bg-blue-500/10 text-blue-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "qualificacao-leads",
    nome: "Qualificação de Leads",
    descricao: "Identifica e classifica potenciais clientes com base em critérios personalizados.",
    categoria: "vendas",
    icone: "Filter",
    cor: "bg-green-500/10 text-green-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "lembretes-aniversario",
    nome: "Lembretes de Aniversário",
    descricao: "Envia mensagens automáticas de felicitações em datas especiais dos clientes.",
    categoria: "relacionamento",
    icone: "Gift",
    cor: "bg-pink-500/10 text-pink-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "notificacoes-estoque",
    nome: "Notificações de Estoque",
    descricao: "Avisa clientes quando produtos desejados voltam ao estoque.",
    categoria: "vendas",
    icone: "Package",
    cor: "bg-amber-500/10 text-amber-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "campanhas-sazonais",
    nome: "Campanhas Sazonais",
    descricao: "Cria e gerencia campanhas automáticas para datas comemorativas.",
    categoria: "marketing",
    icone: "Calendar",
    cor: "bg-red-500/10 text-red-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "reengajamento-clientes",
    nome: "Reengajamento de Clientes",
    descricao: "Recupera clientes inativos com ofertas personalizadas baseadas em histórico.",
    categoria: "relacionamento",
    icone: "RefreshCw",
    cor: "bg-violet-500/10 text-violet-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "analise-sentimento",
    nome: "Análise de Sentimento",
    descricao: "Monitora e analisa o sentimento das interações com clientes.",
    categoria: "feedback",
    icone: "BarChart2",
    cor: "bg-orange-500/10 text-orange-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "segmentacao-clientes",
    nome: "Segmentação de Clientes",
    descricao: "Agrupa clientes com base em comportamento, histórico e preferências.",
    categoria: "marketing",
    icone: "Users",
    cor: "bg-emerald-500/10 text-emerald-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "chatbot-whatsapp",
    nome: "Chatbot para WhatsApp",
    descricao: "Automatiza conversas no WhatsApp com respostas inteligentes.",
    categoria: "atendimento",
    icone: "MessageCircle",
    cor: "bg-green-500/10 text-green-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "pesquisa-nps",
    nome: "Pesquisa NPS",
    descricao: "Coleta e analisa o Net Promoter Score dos seus clientes.",
    categoria: "feedback",
    icone: "Star",
    cor: "bg-yellow-500/10 text-yellow-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "cupons-personalizados",
    nome: "Cupons Personalizados",
    descricao: "Gera e envia cupons de desconto baseados no perfil do cliente.",
    categoria: "vendas",
    icone: "Tag",
    cor: "bg-blue-500/10 text-blue-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "onboarding-clientes",
    nome: "Onboarding de Clientes",
    descricao: "Guia novos clientes com mensagens sequenciais educativas.",
    categoria: "relacionamento",
    icone: "UserPlus",
    cor: "bg-indigo-500/10 text-indigo-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "notificacoes-eventos",
    nome: "Notificações de Eventos",
    descricao: "Envia lembretes automáticos sobre eventos, webinars e lançamentos.",
    categoria: "marketing",
    icone: "Bell",
    cor: "bg-purple-500/10 text-purple-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "recuperacao-carrinho",
    nome: "Recuperação de Carrinho",
    descricao: "Resgata vendas perdidas com lembretes de carrinho abandonado.",
    categoria: "vendas",
    icone: "ShoppingCart",
    cor: "bg-red-500/10 text-red-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "cross-selling",
    nome: "Cross-Selling Automático",
    descricao: "Sugere produtos complementares com base nas compras anteriores.",
    categoria: "vendas",
    icone: "GitBranch",
    cor: "bg-cyan-500/10 text-cyan-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "up-selling",
    nome: "Up-Selling Inteligente",
    descricao: "Oferece versões premium de produtos com base no interesse do cliente.",
    categoria: "vendas",
    icone: "TrendingUp",
    cor: "bg-emerald-500/10 text-emerald-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "fidelizacao-clientes",
    nome: "Programa de Fidelização",
    descricao: "Gerencia pontos, recompensas e níveis de fidelidade automaticamente.",
    categoria: "relacionamento",
    icone: "Award",
    cor: "bg-amber-500/10 text-amber-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "recomendacao-produtos",
    nome: "Recomendação de Produtos",
    descricao: "Sugere produtos personalizados com base no histórico e preferências.",
    categoria: "vendas",
    icone: "Gift",
    cor: "bg-pink-500/10 text-pink-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "monitoramento-redes",
    nome: "Monitoramento de Redes Sociais",
    descricao: "Acompanha e responde menções da sua marca nas redes sociais.",
    categoria: "redes-sociais",
    icone: "Activity",
    cor: "bg-blue-500/10 text-blue-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "publicacao-automatica",
    nome: "Publicação Automática",
    descricao: "Programa e publica conteúdo nas redes sociais automaticamente.",
    categoria: "redes-sociais",
    icone: "Clock",
    cor: "bg-indigo-500/10 text-indigo-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "gerenciamento-comentarios",
    nome: "Gerenciamento de Comentários",
    descricao: "Monitora e responde comentários nas redes sociais automaticamente.",
    categoria: "redes-sociais",
    icone: "MessageCircle",
    cor: "bg-purple-500/10 text-purple-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "analise-concorrentes",
    nome: "Análise de Concorrentes",
    descricao: "Monitora e compara sua presença digital com a dos concorrentes.",
    categoria: "marketing",
    icone: "TrendingUp",
    cor: "bg-red-500/10 text-red-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "geracao-leads",
    nome: "Geração de Leads",
    descricao: "Captura e qualifica leads através de formulários e chatbots.",
    categoria: "vendas",
    icone: "UserPlus",
    cor: "bg-green-500/10 text-green-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "automacao-email",
    nome: "Automação de E-mail",
    descricao: "Cria fluxos de e-mails automáticos baseados em gatilhos.",
    categoria: "marketing",
    icone: "Mail",
    cor: "bg-amber-500/10 text-amber-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "pesquisa-mercado",
    nome: "Pesquisa de Mercado",
    descricao: "Coleta e analisa dados de mercado para insights estratégicos.",
    categoria: "marketing",
    icone: "Search",
    cor: "bg-violet-500/10 text-violet-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "gestao-projetos",
    nome: "Gestão de Projetos",
    descricao: "Automatiza tarefas e fluxos de trabalho em projetos.",
    categoria: "administracao",
    icone: "Clipboard",
    cor: "bg-slate-500/10 text-slate-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "automacao-financeira",
    nome: "Automação Financeira",
    descricao: "Automatiza cobranças, faturas e lembretes de pagamento.",
    categoria: "administracao",
    icone: "DollarSign",
    cor: "bg-emerald-500/10 text-emerald-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "gestao-estoque",
    nome: "Gestão de Estoque",
    descricao: "Monitora e alerta sobre níveis de estoque automaticamente.",
    categoria: "administracao",
    icone: "Package",
    cor: "bg-orange-500/10 text-orange-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "analise-vendas",
    nome: "Análise de Vendas",
    descricao: "Gera relatórios e insights automáticos sobre desempenho de vendas.",
    categoria: "vendas",
    icone: "BarChart",
    cor: "bg-blue-500/10 text-blue-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "automacao-rh",
    nome: "Automação de RH",
    descricao: "Automatiza processos de recrutamento, onboarding e gestão de equipe.",
    categoria: "administracao",
    icone: "Users",
    cor: "bg-pink-500/10 text-pink-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "gestao-leads",
    nome: "Gestão de Leads",
    descricao: "Organiza e prioriza leads com base em critérios personalizados.",
    categoria: "vendas",
    icone: "List",
    cor: "bg-indigo-500/10 text-indigo-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "automacao-suporte",
    nome: "Automação de Suporte",
    descricao: "Classifica e encaminha tickets de suporte automaticamente.",
    categoria: "atendimento",
    icone: "LifeBuoy",
    cor: "bg-cyan-500/10 text-cyan-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "chatbot-site",
    nome: "Chatbot para Site",
    descricao: "Implementa um assistente virtual inteligente no seu site.",
    categoria: "atendimento",
    icone: "MessageSquare",
    cor: "bg-green-500/10 text-green-500",
    status: "inativo",
    bloqueado: false,
  },
  {
    id: "automacao-documentos",
    nome: "Automação de Documentos",
    descricao: "Gera e envia documentos personalizados automaticamente.",
    categoria: "administracao",
    icone: "FileText",
    cor: "bg-amber-500/10 text-amber-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "integracao-crm",
    nome: "Integração com CRM",
    descricao: "Sincroniza dados entre plataformas de comunicação e seu CRM.",
    categoria: "administracao",
    icone: "RefreshCw",
    cor: "bg-violet-500/10 text-violet-500",
    status: "inativo",
    bloqueado: true,
    plano: "Enterprise",
  },
  {
    id: "analise-atendimento",
    nome: "Análise de Atendimento",
    descricao: "Monitora e avalia a qualidade dos atendimentos automaticamente.",
    categoria: "atendimento",
    icone: "PieChart",
    cor: "bg-red-500/10 text-red-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "automacao-marketing",
    nome: "Automação de Marketing",
    descricao: "Cria e gerencia campanhas de marketing multicanal.",
    categoria: "marketing",
    icone: "Zap",
    cor: "bg-emerald-500/10 text-emerald-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
  {
    id: "gestao-reputacao",
    nome: "Gestão de Reputação",
    descricao: "Monitora e gerencia avaliações online da sua empresa.",
    categoria: "marketing",
    icone: "Star",
    cor: "bg-yellow-500/10 text-yellow-500",
    status: "inativo",
    bloqueado: true,
    plano: "Premium",
  },
]

// Função para migrar as soluções
async function migrateSolutions() {
  console.log("Iniciando migração de soluções...")

  for (const solucao of solucoes) {
    // Verificar se a solução já existe
    const { data: existingSolution } = await supabase.from("solutions").select("id").eq("slug", solucao.id).single()

    if (existingSolution) {
      console.log(`Solução ${solucao.nome} já existe, atualizando...`)

      // Atualizar solução existente
      const { error } = await supabase
        .from("solutions")
        .update({
          name: solucao.nome,
          description: solucao.descricao,
          category: solucao.categoria,
          icon: solucao.icone,
          color: solucao.cor,
          is_active: solucao.status === "ativo",
          is_premium: solucao.bloqueado || false,
          premium_plan: solucao.plano || null,
          updated_at: new Date().toISOString(),
        })
        .eq("slug", solucao.id)

      if (error) {
        console.error(`Erro ao atualizar solução ${solucao.nome}:`, error)
      }
    } else {
      console.log(`Inserindo nova solução: ${solucao.nome}`)

      // Inserir nova solução
      const { error } = await supabase.from("solutions").insert({
        slug: solucao.id,
        name: solucao.nome,
        description: solucao.descricao,
        category: solucao.categoria,
        icon: solucao.icone,
        color: solucao.cor,
        is_active: solucao.status === "ativo",
        is_premium: solucao.bloqueado || false,
        premium_plan: solucao.plano || null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })

      if (error) {
        console.error(`Erro ao inserir solução ${solucao.nome}:`, error)
      }
    }
  }

  console.log("Migração de soluções concluída!")
}

// Executar a migração
migrateSolutions().catch((error) => {
  console.error("Erro durante a migração:", error)
})
